// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5DTSKDnoOMyrt3xPXFywSt3y74CgmhpY',
    appId: '1:386120161235:web:bbc03b94b6543a7b7e8126',
    messagingSenderId: '386120161235',
    projectId: 'gtfs-cf784',
    authDomain: 'gtfs-cf784.firebaseapp.com',
    storageBucket: 'gtfs-cf784.appspot.com',
    measurementId: 'G-GM2PVWXJBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNoGus0alfgjOCdKIY7Qn3RClFug69aks',
    appId: '1:386120161235:android:970aee2dcd3df1697e8126',
    messagingSenderId: '386120161235',
    projectId: 'gtfs-cf784',
    storageBucket: 'gtfs-cf784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoiPhcV-Il2LmENDgjQbOaEoJFIv0aUgw',
    appId: '1:386120161235:ios:494676a083ceb63b7e8126',
    messagingSenderId: '386120161235',
    projectId: 'gtfs-cf784',
    storageBucket: 'gtfs-cf784.appspot.com',
    iosBundleId: 'com.example.sunBeGone',
  );
}
